site_name: FernAPI
repo_url: https://github.com/Fernthedev/FernAPI/
site_author: Fernthedev
site_description: This API allows for use of code that should work across all server platforms. It aims to allow developers to create better plugins without having inconsistency across platforms and ease their workflow and project workspaces.
copyright: Fernthedev
theme:
  name: 'rtd-dropdown'
